name: .NET Test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore ./Wake.sln
    
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Unit Test
      run: dotnet test --configuration Release --no-build --verbosity normal ./Products/Tests/Wake.Products.UnitTests.csproj

    - name: Integration Test
      run: dotnet test --configuration Release --no-build --verbosity normal ./Products/Tests/Wake.Products.IntegrationTests.csproj
